site_name: Moje projekty
site_author: Jen
site_description: >-
  Portfolio moich wspaniałych projektów z Data Science i AI!

theme:
  name: material
  palette:
    primary: teal

nav:
  - Strona Domowa: index.md
  - Obecny projekt:
      - "Titanic": titanic/index.md
  - Poprzednie projekty:
      - "Iris": iris/index.md
