site_name: Moje projekty
site_author: Jen
site_description: >-
  Portfolio moich wspaniałych projektów z Data Science i AI!

repo_name: jen/ds_ai_portfolio
repo_url: https://github.com/jen/ds_ai_portfolio

theme:
  name: material
  palette:
    primary: teal

nav:
  - Strona Domowa: index.md
  # - Obecny projekt:
  # - "Titanic": titanic/index.md
  - Poprzednie projekty:
      - "Titanic": titanic/index.md
      - "Iris": iris/index.md
